apiVersion: apps/v1
kind: Deployment
metadata:
  name: johanbos-deployment
spec:
  selector:
    matchLabels:
      app: johanbos
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: johanbos
    spec:
      containers:
        - name: johanbos
          image: johanbosnl/johanbos:latest
          ports:
            - containerPort: 80
              hostPort: 5000
