apiVersion: apps/v1
kind: Deployment
metadata:
  name: johanbos-api-deployment
spec:
  selector:
    matchLabels:
      app: johanbos-api
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: johanbos-api
    spec:
      containers:
        - name: johanbos-api
          image: johanbosnl/johanbos.api:latest
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: johanbos-api-service
spec:
  type: LoadBalancer
  selector:
    app: johanbos-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
