apiVersion: apps/v1
kind: Deployment
metadata:
  name: johanbos-deployment
spec:
  selector:
    matchLabels:
      app: johanbos
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: johanbos
    spec:
      containers:
        - name: johanbos
          image: johanbosnl/johanbos:latest
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: johanbos-service
spec:
  type: LoadBalancer
  selector:
    app: johanbos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
